# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 792878e6e37565d2c3114bb2cdc243979ca7cf3cd87fefff43047f3be0d3cd9be32d7d41218419ac5346ab06e27cc5eaf965e9982069e98f1008aeee2dee90ed

test:
  secret_key_base: 39d41c8079b37c9f099fcb3c668299de0534859acc054bc23147a696efc70f03d976b52abfe92171b943d9b49830e0f59a481a51e1486cd7fb8eafd028da7dee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
